# Generated by Django 6.0.5 on 2026-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_sport_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'time_slot', 'booking_date'], name='api_booking_venue_i_e43abb_idx'),
        ),
    ]
