# Generated by Django 6.0.5 on 2026-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_token_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('WALLET', 'Wallet'), ('CASH', 'Cash'), ('ESEWA', 'eSewa'), ('PAY_AT_VENUE', 'Pay at Venue')], max_length=20),
        ),
    ]
