# Generated by Django 6.0.5 on 2026-07-02 16:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_home_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueRating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_ratings', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.venue')),
            ],
            options={
                'verbose_name': 'Venue Rating',
                'verbose_name_plural': 'Venue Ratings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venue'], name='api_venuera_venue_i_a2d929_idx')],
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
