# Generated by Django 6.0.3 on 2026-07-08 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_venue_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_slots',
            field=models.ManyToManyField(blank=True, related_name='bookings_multi', to='api.timeslot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='api.timeslot'),
        ),
    ]
